### ISSUE TITLE
Pagination for results

### ISSUE THREAD

**Issue by gear54rus** [odin-public/RESTClient-APS#31]
Might be nice.

**Comment by gear54rus** [comment]
No clear design or drivers for this. Vote if you need it.

**Comment by mastacheata** [comment]
What kind of results did you have in mind when thinking about pagination for the results?
I can't imagine paging JSON or XML (including HTML) results at all.

I'll suggest another approach to compacting JSON responses in a separata issue, in a minute, though.

**Comment by gear54rus** [comment]
That was just a vaguely-worded request by some people so I had nothing in mind. Perhaps collapsing is really better (it really makes more sense). Will see when I have time.

**Comment by gear54rus** [comment]
#42 is to be merged, this is considered finished.
