### ISSUE TITLE
Not working on FF 46.0.1

### ISSUE THREAD

**Issue by albertotn** [odin-public/RESTClient-APS#37]
It's not working on FF 46.0.1, maybe related to [this issue](https://github.com/chao/RESTClient/issues/220) ?

Test case:
1) download extension from [here](https://github.com/odin-public/RESTClient-APS/releases/tag/v1.6)
2) install xpi directly
3) restart Firefox
4) click RESTClient button on toolbar

Problem: anything shows up or working

Thanks!

**Comment by gear54rus** [comment]
Thanks for reporting, I've posted little something in main thread.

**Comment by gear54rus** [comment]
Fixed in c3781f7be7a32e9ef2361f501e926b4e6a7280a3.

**Comment by albertotn** [comment]
thank you! Works fine on FF 46.0.1 !

**Comment by gear54rus** [comment]
Yeah, thanks to people who investigated this, I just merged it :)
