### ISSUE TITLE
Bookmark import  issue

### ISSUE THREAD

**Issue by mirkoperillo** [odin-public/RESTClient-APS#38]
Hi 

* I exported my bookmarks from original RESTClient.
* I uninstalled it
* I installed RESTClient-APS.
* I tried to import my RESTClient bookmarks in RESTClient-APS.

When I try it a popup says me that _"Cannot import the json file"_ and then I close it another one that says _"import request succeed"_.
When I try to _"See All bookmarks"_ the list is empty.

The strange thing is that if I try to export bookmarks from RESTClient-APS  the resulted json contains all the bookmarks that I tried to import.

**Comment by gear54rus** [comment]
I have not tested this as far as I recall. Can you please share the link (or the xpi) for the original restclient version you used?

**Comment by mirkoperillo** [comment]
Hi,

I uninstalled it before install your addon.
I don't remember RESTClient version number, but I know that I have the updated version, I remember taht the update version was 14 april

**Comment by gear54rus** [comment]
Can you try to share the JSON then?

**Comment by gear54rus** [comment]
I am unable to export any JSON with the current version [available here](https://addons.mozilla.org/en-US/firefox/addon/restclient/).

**Comment by mirkoperillo** [comment]
In attachment an extract of JSON export

I attach .txt at the end of filename to permit github upload
[restclient-expo.json.txt](https://github.com/odin-public/RESTClient-APS/files/272411/restclient-expo.json.txt)

**Comment by gear54rus** [comment]
This seems working. Please try your cases and then report so we can close this.

**Comment by gear54rus** [comment]
Here's an unsigned build for you to try: [restclient-aps.zip](https://github.com/odin-public/RESTClient-APS/files/277361/restclient-aps.zip)

**Comment by gear54rus** [comment]
@mirkoperillo making sure you see the above message :)

**Comment by mirkoperillo** [comment]
Hi,

yes I saw it, I think I'm be able to try it this evening or tomorrow.

Thank you for the fix..I'll give you news about

**Comment by mirkoperillo** [comment]
A question of you..I can test this xpi only with FF dev edition ?
I tried to install on my FF but it blocks it because it is unsigned

**Comment by gear54rus** [comment]
Yes, I've specified that this is an **unsigned build**. I only sign builds for main releases since otherwise people's browsers may forever be stuck with some old version that is not part of the [official line](https://github.com/odin-public/RESTClient-APS/releases).

You could in theory install it on an earlier versions which doesn't require signing, or you could use FF dev edition which has this option available: https://i.imgur.com/zw8ryqE.png and won't require signing.

**Comment by mirkoperillo** [comment]
Good,

I tried unsigned addon on FF dev edition: I confirm you that import works fine now

**Comment by gear54rus** [comment]
Will include in release.
