### ISSUE TITLE
Bookmark label

### ISSUE THREAD

**Issue by mirkoperillo** [odin-public/RESTClient-APS#39]
I tried to give a label when I bookmarked a request, but when I opened the list of my bookmarks I saw the request with **uncategorized** label

**Comment by gear54rus** [comment]
Yeah, labels probably don't work as well. I'll try to find a way to fix the leftover code from the original.

**Comment by gear54rus** [comment]
Labels seem to be more complicated than initially thought.

If someone can provide a working pull request, I will merge it and revert the above commit, but for now I simply removed UI handles to that so people don't try to mistakenly use it.

This stays open and gets a 'help wanted' label.

**Comment by gear54rus** [comment]
See #54.
