### ISSUE TITLE
Better preview of non-structured response types

### ISSUE THREAD

**Issue by mastacheata** [odin-public/RESTClient-APS#52]
I've got no clear idea for this issue yet, so I'll just put this up for debate.
If you send a GET request to google.com for example, you'll not see the nice Google homepage because all the external resources aren't embedded and in general they are a few levels down in the HTML structure.
Probably the best way to handle that would be to simply have an iframe with the full HTML response you get (same would work for other non-structured types like PDF etc) and let Gecko handle the rendering.

I'm not sure about iframes with inline content, though. Maybe there's another element for that stuff? embed maybe?

This occured to me because we have a few APIs that respond with nicely styled HTML errors if the user agent hints at a "normal" browser.

**Comment by gear54rus** [comment]
> iframe with the full HTML response
> let Gecko handle the rendering

This is going to be a huge performance hit and/or a security risk, don't you think? We are in the clear with security as long as we don't interpret/run any data we get as a response. Perhaps we need to research how `iframes` should be sandboxed properly or otherwise we might run into trouble quite fast. Perhaps you know of other REST Client which has that functionality?

**Comment by mastacheata** [comment]
I've got no idea about the sandboxing of iframes and didn't even think about that. But that's what I had in mind with an open discussion.

The Advanced REST Client of Chrome has that functionality:
https://github.com/jarrodek/ChromeRestClient/blob/develop/app/scripts/html-preview.js
https://github.com/jarrodek/ChromeRestClient/blob/develop/app/html-preview.html

The html-preview.html is an iframe embedded in the "preview"/"parsed" tab of the response.

Apparently this doesn't load all external resources as well, but at least the css layout looks closer to the original than the one in our Fx REST Client.

**Comment by gear54rus** [comment]
No idea when I will get to this, but looks interesting.

**Comment by gear54rus** [comment]
See #54.
